spring:
  batch:
    job:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/promo_graud_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:59056}
      timeout: 2000ms

server:
  port: ${BACKEND_PORT:8080}

jwt:
  secret: 20b84f35360762f63e3f9a00d82ea614b53a207dbb842ada7cd869e35e214a94
  refresh-secret: 659079efaa0f77794f8bb02b664e608dbec37d700acdd238f951e82611d647c0
  valid-duration: 900
  refresh-duration: 72000

voucher:
  batch:
    unique-threshold: 50         # UNIQUE >= số này thì chạy bằng batch
    chunk-size: 20               # số bản ghi mỗi lần commit


